
#:schema node_modules/wrangler/config-schema.json
name = "adex-manager"
pages_build_output_dir = "."

# ğŸ› ï¸ LOKALNA KONFIGURACIJA
# Ova datoteka se koristi samo za lokalni razvoj (npm run dev).
# Cloudflare Pages je ignorira, Å¡to nam omoguÄ‡uje ruÄno postavljanje bindinga u Dashboardu.

[[kv_namespaces]]
binding = "AD_EXCLUSION_KV_DEV"
id = "2b0b48a8f41b4d02ad878ea0181c1207"
preview_id = "2b0b48a8f41b4d02ad878ea0181c1207"
